version: '3.4'

services:
  project:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  mysqldb:
    container_name: user-db
    image: mysql:8
    networks:
      - user-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    # restart: on-failure

networks:
  user-mysql:
